version: '3.8'
services:
  mongo:
    image: mongo:6.0
    container_name: Banking-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: Banking-backend
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=write your mongodb url either atlas or local
      - JWT_SECRET=write your jwt secret key
    depends_on:
      - mongo
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: Banking-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongo-data:
